"""make_user_id_nullable

Revision ID: 305e347906e1
Revises: 31b7529ae8f0
Create Date: 2026-06-08 12:23:42.955129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305e347906e1'
down_revision: Union[str, Sequence[str], None] = '31b7529ae8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('runs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('files', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
