import { Link } from "react-router-dom";
import { TeamStoaIcon } from "@/components/layout/TeamStoaIcon";

export function TermsPage() {
  return (
    <div className="min-h-dvh flex flex-col bg-[var(--bg)]">
      <header className="border-b border-border px-4 py-3 pt-safe">
        <div className="mx-auto flex w-full max-w-[780px] items-center justify-between gap-3">
          <Link to="/" className="flex items-center gap-2.5 hover:opacity-80 transition">
            <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-gradient-to-br from-violet-700 to-violet-400 shadow-md">
              <TeamStoaIcon className="h-5 w-5" />
            </div>
            <span className="font-bold text-base tracking-tight text-foreground">
              Team<span className="text-violet-700">Stoa</span>
            </span>
          </Link>
          <nav className="flex items-center gap-4 text-sm text-muted-foreground">
            <Link to="/about" className="hover:text-foreground transition">About</Link>
            <Link to="/privacy" className="hover:text-foreground transition">Privacy</Link>
          </nav>
        </div>
      </header>

      <main className="mx-auto w-full max-w-[780px] flex-1 px-4 py-10 pb-safe">
        <h1 className="font-display text-2xl font-bold text-foreground mb-1">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: July 2026</p>

        <div className="prose prose-sm dark:prose-invert max-w-none space-y-8 text-foreground">

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">Acceptance</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              By creating an account or using TeamStoa you agree to these Terms of Service and
              our <Link to="/privacy" className="text-violet-600 dark:text-violet-400 underline hover:opacity-80 transition">Privacy Policy</Link>.
              If you do not agree, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">What TeamStoa is</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              TeamStoa is a multi-agent AI debate platform. You pose a question; a team of AI
              models debates it across multiple rounds and returns a consensus answer. AI responses
              are generated by third-party models via OpenRouter and are not reviewed or verified
              by TeamStoa before being shown to you.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">AI accuracy and reliance</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              AI-generated responses may be incorrect, incomplete, or outdated.
              <strong> Do not use TeamStoa as your sole basis for medical, legal, financial, or
              safety-critical decisions.</strong> Always verify important outputs with qualified
              professionals or authoritative sources. TeamStoa makes no warranty as to the accuracy,
              completeness, or fitness for any purpose of AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">Acceptable use</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              You agree not to use TeamStoa to:
            </p>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-5 space-y-1 mt-2">
              <li>Generate content that is illegal, harmful, threatening, or abusive</li>
              <li>Attempt to circumvent usage quotas through multiple accounts or automated requests</li>
              <li>Probe, attack, or disrupt the service or its infrastructure</li>
              <li>Resell or sublicense access to the service</li>
            </ul>
            <p className="text-sm text-muted-foreground leading-relaxed mt-3">
              We reserve the right to suspend or terminate accounts that violate these rules.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">Usage quotas</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Free accounts are subject to a monthly run limit. The quota resets at the start of
              each calendar month. We may adjust quota limits at any time; we will provide notice
              of significant reductions to active users.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">Your content</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              You retain ownership of the questions you submit. AI-generated responses belong to
              you to the extent permitted by the underlying model providers' terms. By using the
              public sharing feature you grant TeamStoa a non-exclusive licence to serve that
              content to people who access the shared link.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">Limitation of liability</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              TeamStoa is provided "as is" without warranty of any kind. To the maximum extent
              permitted by law, TeamStoa and its operators are not liable for any indirect,
              incidental, or consequential damages arising from your use of the service, including
              but not limited to losses arising from reliance on AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">Changes to these terms</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We may update these terms as the product evolves. We will update the date at the top
              of this page when changes are made. Continued use of TeamStoa after a terms update
              constitutes acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">Contact</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Questions about these terms: <a href="mailto:hello@teamstoa.com" className="text-violet-600 dark:text-violet-400 underline hover:opacity-80 transition">hello@teamstoa.com</a>
            </p>
          </section>

        </div>
      </main>

      <footer className="border-t border-border px-4 py-5 text-center text-xs text-muted-foreground/60">
        <div className="flex items-center justify-center gap-4">
          <span>© {new Date().getFullYear()} TeamStoa</span>
          <Link to="/terms" className="underline hover:text-muted-foreground transition">Terms</Link>
          <Link to="/privacy" className="underline hover:text-muted-foreground transition">Privacy</Link>
          <Link to="/about" className="underline hover:text-muted-foreground transition">About</Link>
        </div>
      </footer>
    </div>
  );
}
